# Generated by Django 5.1.6 on 2025-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
